columns:
  age: int
  default: int
  balance: int
  housing: int
  loan: int
  contact: int
  day: int
  month: int
  duration: int
  campaign: int
  previous: int
  y: int
  job_blue-collar: int
  job_entrepreneur: int
  job_housemaid: int
  job_management: int
  job_retired: int
  job_self-employed: int
  job_services: int
  job_student: int
  job_technician: int
  job_unemployed: int
  marital_married: int
  marital_single: int
  edu_primary: int
  edu_secondary: int


numerical_columns:
  age: int
  default: int
  balance: int
  housing: int
  loan: int
  contact: int
  day: int
  month: int
  duration: int
  campaign: int
  previous: int
  y: int
  job_blue-collar: int
  job_entrepreneur: int
  job_housemaid: int
  job_management: int
  job_retired: int
  job_self-employed: int
  job_services: int
  job_student: int
  job_technician: int
  job_unemployed: int
  marital_married: int
  marital_single: int
  edu_primary: int
  edu_secondary: int

