columns:
  - age: int
  - balance: int
  - day: int
  - duration: int
  - campaign: int
  - previous: int
  - job: category
  - marital: category
  - education: category
  - default: category
  - housing: category
  - loan: category
  - contact: category
  - month: category
  - y: category
  


transform_columns:  # This will use power Transformation Technique
  - age
  - balance
  - duration
  - campaign
  - previous
 
ohe_columns:
  - job
  - marital
  - education

ord_columns:
  - default
  - housing
  - loan
  - contact
  - month
  
impute_columns:
  - job
  - education
  - contact


numerical_columns:
  - age: int
  - balance: int
  - day: int
  - duration: int
  - campaign: int
  - previous: int

categorical_columns:
  job: category
  marital: category
  education: category
  default: category
  housing: category
  loan: category
  contact: category
  month: category
  y: category


target_column:
  y: category


  domain_value:
    job:
     - admin. 
     - blue-collar 
     - entrepreneur
     - housemaid 
     - management
     - retired 
     - self-employed
     - services
     - student 
     - technician
     - unemployed 
     - unknown
    
    marital:
    
      - "divorced"
      - "married"
      - "single"
      - "unknown"
    education:
    
      - "primary"
      - "secondary"
      - "tertiary"
      - "unknown"
    
    default:
      - "no"
      - "yes"
      - "unknown"
    
    housing:
      - "no"
      - "yes"
      - "unknown"
    
    loan:
      - "no"
      - "yes"
      - "unknown"
    
    contact:
      - "cellular"
      - "telephone" 
   
    month:
      - "jan"
      - "feb"
      - "mar"
      - "apr"
      - "may"
      - "jun"
      - "jul"
      - "aug"
      - "sep"
      - "oct"
      - "nov"
      - "dec"
    
    y:
      - "no"
      - "yes"



  