columns:
  age: int
  balance: int
  day: int
  duration: int
  campaign: int
  previous: int
  job: string
  marital: string
  education: string
  default: string
  housing: string
  loan: string
  contact: string
  month: string
  y: string
  


numerical_columns:
  age: int
  balance: int
  day: int
  duration: int
  campaign: int
  previous: int

categorical_columns:
  job: string
  marital: string
  education: string
  default: string
  housing: string
  loan: string
  contact: string
  month: string
  y: string

  domain_value:
    job:
     - admin. 
     - blue-collar 
     - entrepreneur
     - housemaid 
     - management
     - retired 
     - self-employed
     - services
     - student 
     - technician
     - unemployed 
     - unknown
    
    marital:
    
      - "divorced"
      - "married"
      - "single"
      - "unknown"
    education:
    
      - "primary"
      - "secondary"
      - "tertiary"
      - "unknown"
    
    default:
      - "no"
      - "yes"
      - "unknown"
    
    housing:
      - "no"
      - "yes"
      - "unknown"
    
    loan:
      - "no"
      - "yes"
      - "unknown"
    
    contact:
      - "cellular"
      - "telephone" 
   
    month:
      - "jan"
      - "feb"
      - "mar"
      - "apr"
      - "may"
      - "jun"
      - "jul"
      - "aug"
      - "sep"
      - "oct"
      - "nov"
      - "dec"
    
    y:
      - "no"
      - "yes"